apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    app: grafana
    app.kubernetes.io/name: grafana
  name: grafana-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "grafana.demo.mzdev.be"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: grafana
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: istio-system
spec:
  hosts:
    - "grafana.demo.mzdev.be"
  gateways:
    - grafana-gateway
  http:
    - route:
        - destination:
            host: grafana
            port:
              number: 3000
