apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: grafana
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: istio-system
spec:
  hosts:
    - grafana-istio.demo.spic.me
  gateways:
    - ingressgateway
  http:
    - route:
        - destination:
            host: grafana
            port:
              number: 3000
