apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    app: kiali
    app.kubernetes.io/name: kiali
  name: kiali-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "kiali.demo.mzdev.be"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: kiali
    app.kubernetes.io/name: kiali
  name: kiali
  namespace: istio-system
spec:
  hosts:
    - "kiali.demo.mzdev.be"
  gateways:
    - kiali-gateway
  http:
    - route:
        - destination:
            host: kiali
            port:
              number: 20001
