apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    app: tracing
    app.kubernetes.io/name: tracing
  name: tracing-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "tracing.demo.mzdev.be"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: tracing
    app.kubernetes.io/name: tracing
  name: tracing
  namespace: istio-system
spec:
  hosts:
    - "tracing.demo.mzdev.be"
  gateways:
    - tracing-gateway
  http:
    - route:
        - destination:
            host: tracing
            port:
              number: 80
