dependencies:
- name: chartmuseum
  version: 1.5.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: docker-registry
  version: 1.4.4
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: jenkins
  version: 0.16.6
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: sonatype-nexus
  version: 1.5.1
  repository: https://kubernetes-charts.storage.googleapis.com/
