apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: APPLICATION-PHASE-tls
  namespace: NAMESPACE
spec:
  secretName: APPLICATION-PHASE-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: APPLICATION-PHASE.BASE_DOMAIN
  dnsNames:
    - APPLICATION-PHASE.BASE_DOMAIN
  acme:
    config:
      - http01:
          ingress: APPLICATION-PHASE
        domains:
          - APPLICATION-PHASE.BASE_DOMAIN
