# ------------------- Ingress ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server
  namespace: devops
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: argocd-server-devops.demo.mzdev.be
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: http
  tls:
  - hosts:
    - argocd-server-devops.demo.mzdev.be
    secretName: argocd-server-mzdev-tls
