# ------------------- Deployment ------------------- #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {DEPLOY_NAME}
  namespace: {NAMESPACE}
  labels:
    app: {DEPLOY_NAME}
spec:
  replicas: {REPLICAS}
  selector:
    matchLabels:
      k8s-app: {DEPLOY_NAME}
  template:
    metadata:
      labels:
        k8s-app: {DEPLOY_NAME}
    spec:
      containers:
      - name: {DEPLOY_NAME}
        image: {IMAGE_REPO}/{IMAGE_NAME}:{IMAGE_TAG}
        ports:
        - containerPort: {CONTANER_PORT}
          protocol: TCP

---
# ------------------- Service ------------------- #

apiVersion: v1
kind: Service
metadata:
  name: {DEPLOY_NAME}
  namespace: {NAMESPACE}
  labels:
    app: {DEPLOY_NAME}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  type: {SERVICE_TYPE}
  ports:
    - port: {SERVICE_PORT}
      targetPort: {CONTANER_PORT}
  selector:
    k8s-app: {DEPLOY_NAME}

---
# ------------------- Ingress ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {DEPLOY_NAME}
  namespace: {NAMESPACE}
  labels:
    app: {DEPLOY_NAME}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {DEPLOY_NAME}.apps.nalbam.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {DEPLOY_NAME}
          servicePort: {SERVICE_PORT}

---
# ------------------- HorizontalPodAutoscaler ------------------- #

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {DEPLOY_NAME}
  namespace: {NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {DEPLOY_NAME}
  minReplicas: {REPLICAS_MIN}
  maxReplicas: {REPLICAS_MAX}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {TARGET_PER}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {TARGET_PER}
  # - type: Pods
  #   pods:
  #     metricName: packets-per-second
  #     targetAverageValue: 1k
