dependencies:
- name: prometheus
  version: 6.10.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: grafana
  version: 1.12.0
  repository: https://kubernetes-charts.storage.googleapis.com/
