apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-build-
  namespace: default
spec:
  entrypoint: ci-build
  arguments:
    parameters:
      - name: repo
        value: https://github.com/nalbam/sample-node.git
      - name: revision
        value: master
      - name: image
        value: nalbam/sample-node
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

  templates:
    - name: ci-build
      inputs:
        parameters:
          - name: repo
          - name: revision
      steps:
        - - name: build
            template: run-build
        - - name: docker
            template: run-docker

    - name: run-build
      inputs:
        artifacts:
          - name: code
            path: /work/src
            git:
              repo: "{{workflow.parameters.repo}}"
              revision: "{{workflow.parameters.revision}}"
      container:
        image: node:13
        command: [sh, -c]
        args: [
            "
            cd /work/src &&
            git status &&
            npm run build &&
            ls -al
            ",
          ]
        volumeMounts:
          - name: workdir
            mountPath: /work

    - name: run-docker
      container:
        image: opspresso/builder:v0.7.76
        command: [sh, -c]
        args: [
            "
            cd /work/src &&
            docker build -t {{workflow.parameters.image}} . &&
            dicker images
            ",
          ]
        volumeMounts:
          - name: workdir
            mountPath: /work
