apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-node-
spec:
  entrypoint: ci-node
  arguments:
    parameters:
      - name: repo
        value: https://github.com/nalbam/sample-node.git
      - name: revision
        value: master
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

  templates:
    - name: ci-node
      inputs:
        parameters:
          - name: repo
          - name: revision
      steps:
        - - name: build
            template: run-build
            arguments:
              parameters:
                - name: repo
                  value: "{{inputs.parameters.repo}}"
                - name: revision
                  value: "{{inputs.parameters.revision}}"
        - - name: test
            template: run-test

    - name: run-build
      inputs:
        parameters:
          - name: repo
          - name: revision
        artifacts:
          - name: code
            path: /work/src
            git:
              repo: "{{inputs.parameters.repo}}"
              revision: "{{inputs.parameters.revision}}"
      container:
        image: node:12
        command: [sh, -c]
        args: [
            "
            cd /work/src &&
            git status &&
            npm run build
            ",
          ]
        volumeMounts:
          - name: workdir
            mountPath: /work

    - name: run-test
      container:
        image: node:12
        command: [sh, -c]
        args: [
            "
            cd /work/src &&
            npm run test
            ",
          ]
        volumeMounts:
          - name: workdir
            mountPath: /work

    - name: run-docker
      container:
        image: docker
        command: [sh, -c]
        args: [
            "
            cd /work/src &&
            docker build -t ${registry}/${name}:${version} .
            ",
          ]
        volumeMounts:
          - name: workdir
            mountPath: /work
